os:
- linux
sudo: required
dist: xenial
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6

cache:
  directories:
    - $HOME/.pub-cache
before_script:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - mv flutter $HOME/flutter
  - export PATH=$HOME/flutter/bin:$PATH
  - flutter doctor -v
script:
  - ./flutter/bin/flutter pub get
  - ./flutter/bin/cache/dart-sdk/bin/dartfmt -n --set-exit-if-changed ./lib ./test ./example || travis_terminate 1
  - ./flutter/bin/flutter test --coverage --coverage-path=coverage.lcov
after_success:
  - bash <(curl -s https://codecov.io/bash)
cache:
  directories:
    - $HOME/.pub-cache
