include: package:effective_dart/analysis_options.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    todo: error
    include_file_not_found: ignore
linter:
  rules: